import type { Metadata } from "next";
import { Lato, Libre_Franklin } from "next/font/google";
import "./globals.css";

const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
  variable: "--lato",
});

const libreFranklin = Libre_Franklin({
  subsets: ["latin"],
  variable: "--libre-franklin",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className + libreFranklin.className}>
        {children}
      </body>
    </html>
  );
}
