import type { Metadata } from "next";
import { Lato, Libre_Franklin } from "next/font/google";
import "./globals.css";
import ReactQueryClientProvider from "@/components/ReactQueryClientProvider";

const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  variable: "--lato",
  subsets: ["latin"],
});

const libre_franklin = Libre_Franklin({
  variable: "--libre-franklin",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "UP Min Reserve Hub",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <ReactQueryClientProvider>
      <html lang="en" className={`${lato.variable} ${libre_franklin.variable}`}>
        <body>{children}</body>
      </html>
    </ReactQueryClientProvider>
  );
};

export default RootLayout;
